[32m2025-02-07 22:08:33 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - da90651c-8dbe-4c81-b553-7288ac1402ad - 23413 - LOGS_CAPTURED - Started capturing logs in process (pid: 23413).
[32m2025-02-07 22:08:33 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - da90651c-8dbe-4c81-b553-7288ac1402ad - 23413 - processed_data - STEP_START - Started execution of step "processed_data".
[32m2025-02-07 22:08:33 +0000[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - da90651c-8dbe-4c81-b553-7288ac1402ad - 23413 - processed_data - STEP_FAILURE - Execution of step "processed_data" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "processed_data"::

pandas.errors.EmptyDataError: No columns to parse from file

Stack Trace:
  File "/workspaces/dagster/venv/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 56, in op_execution_error_boundary
    yield
  File "/workspaces/dagster/venv/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 480, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/workspaces/dagster/venv/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 127, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/workspaces/dagster/venv/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 115, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "/workspaces/dagster/dagster-quickstart/quickstart/assets.py", line 9, in processed_data
    df = pd.read_csv("data/sample_data.csv")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/dagster/venv/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/dagster/venv/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/dagster/venv/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/dagster/venv/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1898, in _make_engine
    return mapping[engine](f, **self.options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/dagster/venv/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 581, in pandas._libs.parsers.TextReader.__cinit__
[0m
